
name: Run on PR comment

env:
  CODER_AGENT_WEBHOOK: ${{ vars.CODER_AGENT_URL }}/api/v1/github-comment
  REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}

on:
  issue_comment:
    types:
    - created
    - edited

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: echo comment
        run: |
          echo A comment on PR ${{ env.NUMBER }} and BODY ${{ env.BODY }} for repository ${{ env.REPOSITORY_URL }}
          echo Webhook push to ${{ env.CODER_AGENT_WEBHOOK }}
        env:
          NUMBER: ${{ github.event.issue.number }}
          BODY: ${{ github.event.comment.body }}
      
      - name: Call api for coding
        if: ${{ startsWith(github.event.comment.body, '/generate-code') || startsWith(github.event.comment.body, '/generate-tests') }}
        run: |
          curl -s -X POST -H "Content-Type: application/json" \
          -d '{"comment": "${{ env.BODY }}", "repository_url": "${{ env.REPOSITORY_URL}}"}' \
          ${{ env.CODER_AGENT_WEBHOOK }}
        env:
          BODY: ${{ github.event.comment.body }}
          



        
