
name: Run on PR comment

on:
  issue_comment:
    types:
    - created
    - edited

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: echo comment
        run: |
          echo A comment on PR $NUMBER and BODY $BODY for repository $REPOSITORY_URL
        env:
          NUMBER: ${{ github.event.issue.number }}
          BODY: ${{ github.event.comment.body }}
          REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}
      
      - name: Call api for coding
        if: ${{ startsWith(github.event.comment.body, '/code') }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"comment\": "$BODY", \"repository_url\": "$REPOSITORY_URL"}' \
          https://rndxn-78-137-210-16.a.free.pinggy.link/api/v1/github-comment
        env:
          BODY: ${{ github.event.comment.body }}
          REPOSITORY_URL: ${{ github.server_url }}/${{ github.repository }}



        
